wip

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -158,41 +158,51 @@ jobs:
             fi
           fi
 
-  rerun-failed-pull-request:
-#    if: ${{ github.event_name == 'pull_request_review' }}
+  retrigger-failed-prs:
     runs-on: ubuntu-latest
-    permissions: write-all
+#    if: github.event_name == 'pull_request_review'
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          fetch-depth: 0 # Fetch all history for all tags and branches
-      - name: Get last failed pull_request run
+      - name: Retrigger failed PR workflows
         run: |
-          RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=pull_request&status=failure" \
-          | jq '.workflow_runs[0].id')
+          gh run retry --failed --repo ${{ github.repository }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-          COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}" \
-          | jq -r '.head_sha')
-
-          echo "Run ID: $RUN_ID"
-          echo "Commit SHA: $COMMIT_SHA"
-
-          if [[ "$RUN_ID" == "null" || -z "$RUN_ID" ]]; then
-            echo "❌ No failed workflow run found!"
-            exit 1
-          fi
-
-          echo "github repo: ${{ github.repository }}"
-          echo "github ref: ${{ github.event.pull_request_review.pull_request.head.ref }}"
-
-          curl -X POST \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          -H "Accept: application/vnd.github+json" \
-          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/pull-request.yml/dispatches" \
-          -d "{\"ref\": \"${{ github.event.pull_request_review.pull_request.head.ref }}\", \"inputs\": { \"commit\": \"$COMMIT_SHA\" }}"
+#  rerun-failed-pull-request:
+##    if: ${{ github.event_name == 'pull_request_review' }}
+#    runs-on: ubuntu-latest
+#    permissions: write-all
+#    steps:
+##      - name: Checkout repository
+##        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+##        with:
+##          fetch-depth: 0 # Fetch all history for all tags and branches
+#      - name: Get last failed pull_request run
+#        run: |
+#          RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#          "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=pull_request&status=failure" \
+#          | jq '.workflow_runs[0].id')
+#
+#          COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}" \
+#          | jq -r '.head_sha')
+#
+#          echo "Run ID: $RUN_ID"
+#          echo "Commit SHA: $COMMIT_SHA"
+#
+#          if [[ "$RUN_ID" == "null" || -z "$RUN_ID" ]]; then
+#            echo "❌ No failed workflow run found!"
+#            exit 1
+#          fi
+#
+#          echo "github repo: ${{ github.repository }}"
+#          echo "github ref: ${{ github.event.pull_request_review.pull_request.head.ref }}"
+#
+#          curl -X POST \
+#          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#          -H "Accept: application/vnd.github+json" \
+#          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/pull-request.yml/dispatches" \
+#          -d "{\"ref\": \"${{ github.ref }}\", \"inputs\": { \"commit\": \"$COMMIT_SHA\" }}"
 
   setup:
     # long timeout required when cache has to be recreated
