[AAE-32905] - Maybe i was too optimistic

diff --git a/.github/workflows/pull-request-save.yml b/.github/workflows/pull-request-save.yml
--- a/.github/workflows/pull-request-save.yml
+++ b/.github/workflows/pull-request-save.yml
@@ -1,4 +1,4 @@
-name: "pull-request"
+name: "pull-request-save"
 
 on:
   workflow_call:
@@ -25,8 +25,6 @@ on:
       - master
       - develop-patch*
       - master-patch*
-  pull_request_review:
-    types: [submitted, dismissed]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -34,9 +32,7 @@ concurrency:
 
 env:
   BASE_REF: ${{ github.base_ref }}
-  BASE_PR_REF: ${{ github.event.pull_request.base.ref }}
   HEAD_REF: ${{ github.head_ref }}
-  HEAD_PR_REF: ${{ github.event.pull_request.head.ref }}
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   GITHUB_BRANCH: ${{ github.ref_name }}
@@ -45,7 +41,6 @@ env:
   BUILD_ID: ${{ github.run_id }}
   GH_RUN_NUMBER: ${{ github.run_attempt }}
   GH_BUILD_NUMBER: ${{ github.run_id }}
-  GH_PR_NUMBER: ${{github.event.pull_request.number}}
   JOB_ID: ${{ github.run_id }}
   LOG_LEVEL: "ERROR"
   S3_BUILD_BUCKET_SHORT_NAME: ${{ secrets.S3_BUILD_BUCKET_SHORT_NAME }}
@@ -69,7 +64,7 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
       - name: Ensure SHA pinned actions
-        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@4830be28ce81da52ec70d65c552a7403821d98d4 # v3.0.23
+        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@25ed13d0628a1601b4b44048e63cc4328ed03633 # v3.0.22
 
       - name: Check package-lock.json version
         run: |
@@ -82,9 +77,6 @@ jobs:
 
   check-if-pr-is-approved:
     runs-on: ubuntu-latest
-    outputs:
-      isLabeledWithDoNotMerge: ${{ steps.check-label.outputs.isLabeledWithDoNotMerge }}
-      pr_approved: ${{ steps.check-approval.outputs.pr_approved }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -92,10 +84,10 @@ jobs:
          fetch-depth: 0
 
       - name: Get branch name
-        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@45bb8b664779b691f8a21d9fd49e360916726c11 # v8.18.1
+        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@c1236aee36bb9b35c5972819fcf8a4d07572e6cd # v8.16.0
 
       - name: Save commit message
-        uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@45bb8b664779b691f8a21d9fd49e360916726c11 # v8.18.1
+        uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@c1236aee36bb9b35c5972819fcf8a4d07572e6cd # v8.16.0
 
       - name: ci:force flag parser
         shell: bash
@@ -108,22 +100,19 @@ jobs:
               skip_check="true"
           fi
 
-      - name: Check if PR is labeled
-        id: check-label
-        run: |
-          if echo '${{ toJson(github.event.pull_request.labels) }}' | jq -e '.[] | select(.name | contains("do not merge"))'; then
-            echo "::warning::PR is labeled as 'do not merge'"
-            echo "isLabeledWithDoNotMerge=true" >> $GITHUB_ENV
-            echo "isLabeledWithDoNotMerge=true" >> $GITHUB_OUTPUT
-          else
-            echo "PR is not labeled as 'do not merge'"
-            echo "isLabeledWithDoNotMerge=false" >> $GITHUB_ENV
-            echo "isLabeledWithDoNotMerge=false" >> $GITHUB_OUTPUT
-          fi
+      - name: Get PR number
+        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
+        uses: kamatama41/get-pr-number-action@0bcaab5752c0b699149e74667c8ce2f764cbb7fa # v0.9.1
+        id: action
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Check if PR is approved
-        id: check-approval
-        if: env.isLabeledWithDoNotMerge == 'false'
+      - name: show pr number
+        shell: bash
+        run: |
+          echo "PR: ${{ steps.action.outputs.number }}"
+
+      - name: check if pr is approved
         env:
           DEVEL_FLAG: ${{ inputs.devel }}
           GH_TOKEN: ${{ github.token }}
@@ -150,17 +139,17 @@ jobs:
             echo -e "\033[32mDevel flag\033[0m"
             skip_check="true"
           fi
+
           if [ "$skip_check" == "false" ]; then
             echo "Checking PR approval"
-            echo "PR: $GH_PR_NUMBER"
-
-            if gh pr view $GH_PR_NUMBER --json reviews | jq -e '.reviews[] | select(.state == "APPROVED")'; then
+            prNumber=${{ steps.action.outputs.number }}
+            echo "PR: $prNumber"
+            checkApproval=$(gh api /repos/$GITHUB_REPOSITORY/pulls/$prNumber/reviews | jq '.[] | select(.state == "APPROVED") | .user.login')
+            if [[ $checkApproval ]]; then
               echo -e "\033[32mPR approved\033[0m"
-              echo "pr_approved=true" >> $GITHUB_OUTPUT
             else
-              echo "::error::PR NOT approved"
               echo -e "\033[31mPR NOT approved\033[0m"
-              echo "pr_approved=false" >> $GITHUB_OUTPUT
+              exit 1
             fi
           fi
 
@@ -170,7 +159,6 @@ jobs:
     name: "Setup"
     runs-on: ubuntu-latest
     needs: [check-if-pr-is-approved, pre-checks]
-    if: ${{ needs.check-if-pr-is-approved.outputs.isLabeledWithDoNotMerge == 'false' && needs.check-if-pr-is-approved.outputs.pr_approved == 'true' }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -211,7 +199,91 @@ jobs:
 
   trigger-unit-tests:
     name: "Unit Tests"
+    runs-on: ubuntu-latest
     needs: [generate-affected-matrix]
-    uses: ./.github/workflows/unit-test-workflow.yml
-    with:
-      matrix: ${{ needs.generate-affected-matrix.outputs.matrix }}
+    steps:
+      - name: Call unit tests workflow
+        uses: ./.github/workflows/unit-test-workflow.yml@main
+        with:
+          matrix: ${{ needs.generate-affected-matrix.outputs.matrix }}
+
+  lint:
+    # long timeout required when cache has to be recreated
+    timeout-minutes: 30
+    name: "Lint"
+    runs-on: ubuntu-latest
+    needs: [setup]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0 # Fetch all history for all tags and branches
+      - uses: ./.github/actions/setup
+      - run: npx nx affected --target=lint $NX_CALCULATION_FLAGS
+
+  build-libs:
+    # long timeout required when cache has to be recreated
+    timeout-minutes: 30
+    name: "Build libs"
+    runs-on: ubuntu-latest
+    needs: [setup]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0 # Fetch all history for all tags and branches
+      - uses: ./.github/actions/setup
+      - uses: ./.github/actions/download-node-modules-and-artifacts
+      - run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 npx nx affected:build $NX_CALCULATION_FLAGS --prod
+      - run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 npx nx affected --target=build-storybook $NX_CALCULATION_FLAGS --configuration=ci
+      - uses: ./.github/actions/upload-node-modules-and-artifacts
+
+  PR-forbidden-labels:
+    if: ${{ inputs.cron-run == '' || inputs.cron-run == 'false' }}
+    runs-on: ubuntu-latest
+    steps:
+      - id: checkoutRepo
+        name: Checkout repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 1
+      - name: PR contains forbidden labels
+        id: pr-forbidden
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        with:
+          script: |
+            const issueHasLabels = require('./scripts/github/update/check-issue-has-label.js');
+            const checkLabels = ['next version ➡️', 'do not merge🙅🏻‍♂️'];
+
+            const hasLabel = await issueHasLabels({github, context, checkLabels})
+
+            if(hasLabel) {
+              core.setFailed('The PR contains a forbidden label! You are not allowed to merge until the label is there.');
+            }
+      - name: Check value after
+        run: |
+          echo "result ${{ toJson(steps.pr-forbidden.*.result) }}" && echo "result ${{ steps.pr-forbidden.*.result }}"
+          echo "result ${{ contains(toJson(steps.pr-forbidden.*.result), 'failure') }}"
+
+  finalize:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    name: Final Results
+    needs: [check-if-pr-is-approved, pre-checks, setup, trigger-unit-tests, lint, build-libs]
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: identify-slack-group
+        id: groups
+        if: ${{ github.event_name == 'schedule' }}
+        uses: ./.github/actions/slack-group-area
+        with:
+          affected: ${{ steps.e2e-result.outputs.result }}
+      - name: workflow failure
+        run: exit 1
+        if: ${{ contains(needs.*.result, 'failure') }}
+      - name: workflow canceled
+        run: exit 1
+        if: ${{ contains(needs.*.result, 'cancelled') }}
+      - name: workflow success
+        run: exit 0
+        if: ${{ contains(needs.*.result, 'success') }}
